name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: lock-threads

permissions: {}
jobs:
  lock:
    permissions:
      issues: write
      pull-requests: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          github-token: ${{ github.token }}
          process-only: 'issues, prs'
          issue-inactive-days: '60'
          issue-comment: >
            This issue has been automatically locked since there has not been any recent activity after it was closed.
            Please open a new issue for related issues and reference this one.

          pr-inactive-days: '60'
          pr-comment: >
            This pull request has been automatically locked since there has not been any recent activity after it was 
            closed. Please open a new issue for related bugs and reference this one.
